after_build:
    - cmd: |
          forfiles /m *.proj /S /C "cmd /C msbuild @path"
artifacts:
    - path: 'Build\*.zip'
build:
    verbosity: detailed
before_build:
    - cmd: |
          nuget restore
image: Visual Studio 2019 Preview
pull_requests:
    do_not_increment_build_number: true
skip_tags: true
